# Generated by Django 5.0.14 on 2026-04-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suite_id', models.CharField(max_length=128)),
                ('status', models.CharField(default='completed', max_length=32)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=32)),
                ('model_label', models.CharField(blank=True, max_length=256)),
                ('prompt', models.TextField()),
                ('output_text', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('deterministic', models.JSONField(blank=True, null=True)),
                ('judge', models.JSONField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bench.benchmarkrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
